### ISSUE TITLE
asyncpg + pugsql

### ISSUE THREAD

**Issue by kwuite** [mcfunley/pugsql#2]
Dear Mister Mcfunly,

Would this library work with https://github.com/MagicStack/asyncpg ?

I found https://github.com/loop0/pugsql 6 months ago. Have you taken over development or is the a pure coincidence in naming the library?

Thanks in advance.

Sine cera,
Kelvin

**Comment by mcfunley** [comment]
This library depends on SQLAlchemy to handle connections and present a unified dialect for named parameters.

I'm not really familiar with asyncpg, but it looks like it might work if you try this SQLAlchemy adapter? https://github.com/CanopyTax/asyncpgsa

Re: the other project it's coincidence. I think it's just the obvious riff on "hugsql for python." Looks like I just won the race to pypi.
