### ISSUE TITLE
UTF-8 support?

### ISSUE THREAD

**Issue by eabra** [mcfunley/pugsql#20]
Hi,

is there a way to specify utf8 encoding when connecting to the (sqlite) database?
I have utf8 content in the database and it gets back mangled.

Cheers

**Comment by mcfunley** [comment]
I haven't tried this but this makes it sound like you can just add `?charset=utf-8` to the connection string:
https://stackoverflow.com/a/10819357

Failing that you can also configure the engine yourself, i.e.

```python
from sqlalchemy import create_engine
import pugsql

eng = create_engine(custom_params)

m = pugsql.module('sql/')
m.set_engine(eng)
```

**Comment by mcfunley** [comment]
Let me know / feel free to reopen if that doesn't work
