### ISSUE TITLE
JSON/JSONB columns support in postgresql?

### ISSUE THREAD

**Issue by kykim** [mcfunley/pugsql#36]
does pugsql support inserting/updating a json/jsonb column in postgresql with a python dict?
if so, how would i construct my query?
thanks.

**Comment by mcfunley** [comment]
Great question--in general the param support is provided by sqlalchemy, and I'm not sure how that works with sqlalchemy. What happens if you try?

**Comment by mcfunley** [comment]
The query would just be something like `insert into foo (bar) values :bar` - there's no typing in the query language (as yet). 

Parsing the sql to implement typing not provided by sqlalchemy is something I've thought about doing, but, it hasn't actually been necessary to support anything yet. There's always some way to do things with raw sqlalchemy, even if it's hard to figure out initially. 

If this does work, it'd be great to get it documented.

**Comment by kykim** [comment]
if i dump the dictionary to a string via `json.dumps`, and pass that into the query, it works!
your pointer to sqlalchemy param processing got me thinking in this direction.

Thanks!
