### ISSUE TITLE
Improve errors when calling methods without keyword params

### ISSUE THREAD

**Issue by mcfunley** [mcfunley/pugsql#39]
See discussion in issue: https://github.com/mcfunley/pugsql/issues/38

When calling a query method as:
```
queries.foo(1, 2)
```

Rather than:
```
queries.foo(a=1, b=2)
```

You get an unhelpful error. Ideally the exception text would tell you to use kwargs.

**Comment by Yeganloo** [comment]
Is it good idea to catch the exception and raise a new one with new message?
I am not good with try cache as they effect on performance, specially not on the data-layer!
Can pugsql compiler detect if the queries are using keys or positional arguments?
Of-course it make compiler more complex but this way it is possible to use python typing system and prevent this kind of problems, beside no overhead in runtime will be added!

**Comment by mcfunley** [comment]
Fixed here https://github.com/mcfunley/pugsql/commit/9c36a104584c76848d2a4f08f2dad08f1905c295
