### ISSUE TITLE
Nested Transaction

### ISSUE THREAD

**Issue by Yeganloo** [mcfunley/pugsql#40]
As Sqlalchemy and most of database-engines support nested transaction, why Pugsql not support it?

**Comment by Yeganloo** [comment]
It seems that you planned to support nested transactions, so i report a bug:
If nested transaction commit and outer one do a role back, entire transaction will be committed!
Did you commit outer transaction before/after opening new one?

**Comment by Yeganloo** [comment]
There is no nested transaction!
Code is generating parallel transactions!

**Comment by Yeganloo** [comment]
There is no nested transaction.
Transaction is singleton.

**Comment by mcfunley** [comment]
Added your fix to 0.2.2. Thank you!
