### ISSUE TITLE
Also support parameterized identifiers (or interpolation)

### ISSUE THREAD

**Issue by doekman** [mcfunley/pugsql#46]
The nice thing about **psql**'s variables is the [interpolation](https://www.postgresql.org/docs/9.2/app-psql.html#APP-PSQL-INTERPOLATION). One could write this:

```
SELECT :'custom_name' as "name", 
       :"custom_column" as "value" 
FROM some_table"`
```

And _psql_ will insert the value of the variable `custom_name` as string literal (single quotes), and `custom_column` as identifier literal (double quotes).

I'm not suggesting implementing the exact same syntax, but it would be handy to parameterise identifier such as schema or table name.

Is this idea fitting for PugSQL? I'm willing to take this idea further.

**Comment by caryfitzhugh** [comment]
FWIW https://github.com/mcfunley/pugsql/pull/45
